stages:
  - hello-world
  - deploy
  - test
  - package

cache:
  key: my-cache
  paths:
    - .m2/repository/

hello-world-job:
 image: alpine:latest
 stage: hello-world
 script: echo "Hello world"

deploy_to_tomcat:
  stage: deploy
  script:
    - sudo /opt/apache-tomcat-7.0.77-dbservice/bin/startup.sh &
    - disown


test-job:
  image: maven:3.6-jdk-11
  stage: test
  script:
   - mvn test

package-job:
  image: maven:3.6-jdk-11
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
    - target.*.jar
    expire_in: 2 hour

