stages:
  - hello-world
  - test
  - package


cache:
  key: my-cache
  paths:
    - .m2/repository/

hello-world-job:
 image: alpine:latest
 stage: hello-world
 script: echo "Hello world"

services:
  - mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD


test-job:
  image: maven:3.6-jdk-11
  stage: test
  script:
   - mvn test

package-job:
  image: maven:3.6-jdk-11
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
    - target.*.jar
    expire_in: 2 hour

